# Generated by Django 6.0.3 on 2026-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, choices=[('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Bafoussam', 'Bafoussam'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua'), ('Maroua', 'Maroua'), ('Ngaoundere', 'Ngaoundere'), ('Buea', 'Buea'), ('Limbe', 'Limbe'), ('Kribi', 'Kribi')], max_length=40),
        ),
        migrations.AddField(
            model_name='shop',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
