# Generated by Django 6.0.3 on 2026-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_moderationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='custom_theme_color',
            field=models.CharField(default='#1B3320', help_text='Couleur de signature (ex: #1B3320)', max_length=7),
        ),
        migrations.AddField(
            model_name='shop',
            name='facebook',
            field=models.CharField(blank=True, help_text='Lien Facebook ou nom de page', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='facebook_followers',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de followers Facebook'),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, help_text="Lien Instagram ou nom d'utilisateur", max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de followers Instagram'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo ou image de profil de la boutique', null=True, upload_to='shops/logos/'),
        ),
    ]
