# Generated by Django 6.0.3 on 2026-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_custom_theme_color_shop_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_time_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_monday',
            field=models.TimeField(blank=True, help_text='Heure de fermeture', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_monday',
            field=models.BooleanField(default=False, help_text='Fermé ce jour'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_monday',
            field=models.TimeField(blank=True, help_text="Heure d'ouverture", null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
