# Generated by Django 6.0.3 on 2026-04-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_closing_time_friday_shop_closing_time_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='facebook_followers',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='instagram_followers',
        ),
    ]
